name: Lint

on: [push]

jobs:
  run-linters:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out Git repository
        uses: actions/checkout@main
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      # Install your linters here
      - name: Run linters
        uses: TQRG/puppet-lint-security-iac@v2.0.0
        run: bundle install
        run: bundle exec rake
        run: gem build puppet_lint_security_iac.gemspec
        run: gem install ./puppet-lint-security-iac-1.0.0.gem
        run: puppet-lint ./*.pp
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
